version: '3'
services:
  poi:
    build:
      context: ../src/poi
      dockerfile: ../src/poi/Dockerfile
    image: tripinsights/poi:1.0

  trips:
    build:
      context: ../src/trips
      dockerfile: ../src/trips/Dockerfile
    image: tripinsights/trips:1.0
  
  user-java:
    build:
      context: ../src/user-java
      dockerfile: ../src/user-java/Dockerfile
    image: tripinsights/user-java:1.0
  
  userprofile:
    build:
      context: ../src/userprofile
      dockerfile: ../src/userprofile/Dockerfile
    image: tripinsights/userprofile:1.0

  tripviewer:
    build:
      context: ../src/tripviewer
      dockerfile: ../src/tripviewer/Dockerfile
    image: tripinsights/tripviewer:1.0